### ISSUE TITLE
Trying to send/receive data form bluetooth device

### ISSUE THREAD

**Issue by llKoull** [xaphod/Bluepeer#1]
Hello!

I need to send/receive data from a custom device that uses Bluetooth 3.0 and It's not MFI.

I used BluetoothManager.framework to find the device, connect and disconnect but now i'm stuck sending and receiving data.

Do you think that it is posible to use your library in this case?

Thanks! :)

**Comment by xaphod** [comment]
Sorry, no, this is a library to send & receive data between two iOS devices
