### ISSUE TITLE
btOnly and SomeClass

### ISSUE THREAD

**Issue by matsyoman** [xaphod/Bluepeer#3]
If I want to init a bluepeerObject, I get a error on the line `let bluepeer = BluepeerObject.init(serviceType: "serviceTypeStr", displayName: nil, queue: nil, serverPort: XaphodUtils.getFreeTCPPort(), overBluetoothOnly: btOnly, bluetoothBlock: nil)`
the btOnly seems like its not exists. Does this needs to be true or false?

And the extensions are called SomeClass, but I get a error. Does these need to be renamed to sessionDelegate,

`extension SomeClass: BluepeerSessionManagerDelegate {
    func peerConnectionRequest(peer: BPPeer, invitationHandler: (Bool) -> Void) {
        // ask the user if they want to accept the incoming connection. 
        // call invitationHandler(true) or invitationHandler(false) accordingly
    }
    func peerDidConnect(peerRole: RoleType, peer: BPPeer) {
        // when a peer has successfully connected
    }
    func peerDidDisconnect(peerRole: RoleType, peer: BPPeer) {
        // when a peer has disconnected (intentionally, or lost connection)
    }
}`

And this one to dataDelegate?

`extension SomeClass: BluepeerDataDelegate {
    func didReceiveData(data: NSData, fromPeer peerID: BPPeer) {
        // received data from BPPeer fromPeer ! do something with it
    }
}`

**Comment by xaphod** [comment]
Hi matsyoman,

`overbluetoothOnly` should be a true/false value (Bool), ie. should Bluepeer be allowed to use wifi and bluetooth (false), or only bluetooth (true)

`extension SomeClass: Bluepeer*` is a Swift feature called class extensions. You can read more about them on the Apple Swift guide. Yes, `SomeClass` should be renamed to your class name, the class you put it in
